version: "3"
services:
  generator:
    image: openapitools/openapi-generator-cli:v4.3.0
    volumes:
      - .:/local
    command:
      - generate
      - -i
      - /local/openapi.yaml
      - -g
      - javascript
      - -o
      - /local
      - -c
      - /local/config.json
  validator:
    image: openapitools/openapi-generator-cli:v4.3.0
    volumes:
      - .:/local
    command:
      - validate
      - -i
      - /local/openapi.yaml
