version: "3"
services:
  generator:
    image: openapitools/openapi-generator-cli:v4.2.2
    volumes:
      - .:/local
    command:
      - generate
      - -i
      - /local/openapi.yaml
      - -g
      - javascript
      - -o
      - /local
  validator:
    image: openapitools/openapi-generator-cli:v4.2.2
    volumes:
      - .:/local
    command:
      - validate
      - -i
      - /local/openapi.yaml
