/**
 * Qoodish API
 * Qoodish API JavaScript Client. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PushNotification from './PushNotification';

/**
 * The CurrentUser model module.
 * @module model/CurrentUser
 * @version 0.0.1
 */
class CurrentUser {
    /**
     * Constructs a new <code>CurrentUser</code>.
     * Current user object from server
     * @alias module:model/CurrentUser
     */
    constructor() { 
        
        CurrentUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CurrentUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CurrentUser} obj Optional instance to populate.
     * @return {module:model/CurrentUser} The populated <code>CurrentUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CurrentUser();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('biography')) {
                obj['biography'] = ApiClient.convertToType(data['biography'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('thumbnail_url')) {
                obj['thumbnail_url'] = ApiClient.convertToType(data['thumbnail_url'], 'String');
            }
            if (data.hasOwnProperty('file_name')) {
                obj['file_name'] = ApiClient.convertToType(data['file_name'], 'String');
            }
            if (data.hasOwnProperty('maps_count')) {
                obj['maps_count'] = ApiClient.convertToType(data['maps_count'], 'Number');
            }
            if (data.hasOwnProperty('following_maps_count')) {
                obj['following_maps_count'] = ApiClient.convertToType(data['following_maps_count'], 'Number');
            }
            if (data.hasOwnProperty('reviews_count')) {
                obj['reviews_count'] = ApiClient.convertToType(data['reviews_count'], 'Number');
            }
            if (data.hasOwnProperty('likes_count')) {
                obj['likes_count'] = ApiClient.convertToType(data['likes_count'], 'Number');
            }
            if (data.hasOwnProperty('push_notification')) {
                obj['push_notification'] = PushNotification.constructFromObject(data['push_notification']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
CurrentUser.prototype['id'] = undefined;

/**
 * @member {String} uid
 */
CurrentUser.prototype['uid'] = undefined;

/**
 * @member {String} email
 */
CurrentUser.prototype['email'] = undefined;

/**
 * @member {String} name
 */
CurrentUser.prototype['name'] = undefined;

/**
 * @member {String} biography
 */
CurrentUser.prototype['biography'] = undefined;

/**
 * @member {String} image_url
 */
CurrentUser.prototype['image_url'] = undefined;

/**
 * @member {String} thumbnail_url
 */
CurrentUser.prototype['thumbnail_url'] = undefined;

/**
 * @member {String} file_name
 */
CurrentUser.prototype['file_name'] = undefined;

/**
 * @member {Number} maps_count
 */
CurrentUser.prototype['maps_count'] = undefined;

/**
 * @member {Number} following_maps_count
 */
CurrentUser.prototype['following_maps_count'] = undefined;

/**
 * @member {Number} reviews_count
 */
CurrentUser.prototype['reviews_count'] = undefined;

/**
 * @member {Number} likes_count
 */
CurrentUser.prototype['likes_count'] = undefined;

/**
 * @member {module:model/PushNotification} push_notification
 */
CurrentUser.prototype['push_notification'] = undefined;






export default CurrentUser;

