/**
 * Qoodish API
 * Qoodih API. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MapDetailBase model module.
 * @module model/MapDetailBase
 * @version 0.0.1
 */
class MapDetailBase {
    /**
     * Constructs a new <code>MapDetailBase</code>.
     * @alias module:model/MapDetailBase
     */
    constructor() { 
        
        MapDetailBase.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MapDetailBase</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MapDetailBase} obj Optional instance to populate.
     * @return {module:model/MapDetailBase} The populated <code>MapDetailBase</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MapDetailBase();

            if (data.hasOwnProperty('place_id')) {
                obj['place_id'] = ApiClient.convertToType(data['place_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('lat')) {
                obj['lat'] = ApiClient.convertToType(data['lat'], 'String');
            }
            if (data.hasOwnProperty('lng')) {
                obj['lng'] = ApiClient.convertToType(data['lng'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} place_id
 */
MapDetailBase.prototype['place_id'] = undefined;

/**
 * @member {String} name
 */
MapDetailBase.prototype['name'] = undefined;

/**
 * @member {String} lat
 */
MapDetailBase.prototype['lat'] = undefined;

/**
 * @member {String} lng
 */
MapDetailBase.prototype['lng'] = undefined;






export default MapDetailBase;

