/**
 * Qoodish API
 * Qoodish API JavaScript Client. 
 *
 * The version of the OpenAPI document: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewUser model module.
 * @module model/NewUser
 * @version 0.2.1
 */
class NewUser {
    /**
     * Constructs a new <code>NewUser</code>.
     * User info from firebase.
     * @alias module:model/NewUser
     */
    constructor() { 
        
        NewUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewUser} obj Optional instance to populate.
     * @return {module:model/NewUser} The populated <code>NewUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewUser();

            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('biography')) {
                obj['biography'] = ApiClient.convertToType(data['biography'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uid
 */
NewUser.prototype['uid'] = undefined;

/**
 * @member {String} token
 */
NewUser.prototype['token'] = undefined;

/**
 * @member {String} display_name
 */
NewUser.prototype['display_name'] = undefined;

/**
 * @member {String} biography
 */
NewUser.prototype['biography'] = undefined;

/**
 * @member {String} image_url
 */
NewUser.prototype['image_url'] = undefined;






export default NewUser;

