/**
 * Qoodish API
 * Qoodih API. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InlineObject1 from '../model/InlineObject1';

/**
* Devices service.
* @module api/DevicesApi
* @version 0.0.1
*/
export default class DevicesApi {

    /**
    * Constructs a new DevicesApi. 
    * @alias module:api/DevicesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the usersDevicesPost operation.
     * @callback module:api/DevicesApi~usersDevicesPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Register device
     * Register device with registration token.
     * @param {module:model/InlineObject1} inlineObject1 
     * @param {module:api/DevicesApi~usersDevicesPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    usersDevicesPost(inlineObject1, callback) {
      let postBody = inlineObject1;
      // verify the required parameter 'inlineObject1' is set
      if (inlineObject1 === undefined || inlineObject1 === null) {
        throw new Error("Missing the required parameter 'inlineObject1' when calling usersDevicesPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['firebaseAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/users/devices', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the usersDevicesRegistrationTokenDelete operation.
     * @callback module:api/DevicesApi~usersDevicesRegistrationTokenDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete device
     * Delete device with registration token.
     * @param {String} registrationToken A valid registration token.
     * @param {module:api/DevicesApi~usersDevicesRegistrationTokenDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    usersDevicesRegistrationTokenDelete(registrationToken, callback) {
      let postBody = null;
      // verify the required parameter 'registrationToken' is set
      if (registrationToken === undefined || registrationToken === null) {
        throw new Error("Missing the required parameter 'registrationToken' when calling usersDevicesRegistrationTokenDelete");
      }

      let pathParams = {
        'registration_token': registrationToken
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['firebaseAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/users/devices/{registration_token}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
