/**
 * Qoodish API
 * Qoodih API. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QoodishApi);
  }
}(this, function(expect, QoodishApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QoodishApi.CurrentUser();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CurrentUser', function() {
    it('should create an instance of CurrentUser', function() {
      // uncomment below and update the code to test CurrentUser
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be.a(QoodishApi.CurrentUser);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property uid (base name: "uid")', function() {
      // uncomment below and update the code to test the property uid
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property biography (base name: "biography")', function() {
      // uncomment below and update the code to test the property biography
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "image_url")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailUrl (base name: "thumbnail_url")', function() {
      // uncomment below and update the code to test the property thumbnailUrl
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property fileName (base name: "file_name")', function() {
      // uncomment below and update the code to test the property fileName
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property mapsCount (base name: "maps_count")', function() {
      // uncomment below and update the code to test the property mapsCount
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property followingMapsCount (base name: "following_maps_count")', function() {
      // uncomment below and update the code to test the property followingMapsCount
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property reviewsCount (base name: "reviews_count")', function() {
      // uncomment below and update the code to test the property reviewsCount
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property likesCount (base name: "likes_count")', function() {
      // uncomment below and update the code to test the property likesCount
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

    it('should have the property pushEnabled (base name: "push_enabled")', function() {
      // uncomment below and update the code to test the property pushEnabled
      //var instane = new QoodishApi.CurrentUser();
      //expect(instance).to.be();
    });

  });

}));
