/**
 * Qoodish API
 * Qoodih API. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QoodishApi);
  }
}(this, function(expect, QoodishApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QoodishApi.MapDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MapDetail', function() {
    it('should create an instance of MapDetail', function() {
      // uncomment below and update the code to test MapDetail
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be.a(QoodishApi.MapDetail);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property ownerId (base name: "owner_id")', function() {
      // uncomment below and update the code to test the property ownerId
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property ownerName (base name: "owner_name")', function() {
      // uncomment below and update the code to test the property ownerName
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property ownerImageUrl (base name: "owner_image_url")', function() {
      // uncomment below and update the code to test the property ownerImageUrl
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property _private (base name: "private")', function() {
      // uncomment below and update the code to test the property _private
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property base (base name: "base")', function() {
      // uncomment below and update the code to test the property base
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property liked (base name: "liked")', function() {
      // uncomment below and update the code to test the property liked
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property likesCount (base name: "likes_count")', function() {
      // uncomment below and update the code to test the property likesCount
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property following (base name: "following")', function() {
      // uncomment below and update the code to test the property following
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property followersCount (base name: "followers_count")', function() {
      // uncomment below and update the code to test the property followersCount
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property editable (base name: "editable")', function() {
      // uncomment below and update the code to test the property editable
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property postable (base name: "postable")', function() {
      // uncomment below and update the code to test the property postable
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property shared (base name: "shared")', function() {
      // uncomment below and update the code to test the property shared
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property invitable (base name: "invitable")', function() {
      // uncomment below and update the code to test the property invitable
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property imageUrl (base name: "image_url")', function() {
      // uncomment below and update the code to test the property imageUrl
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailUrl (base name: "thumbnail_url")', function() {
      // uncomment below and update the code to test the property thumbnailUrl
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new QoodishApi.MapDetail();
      //expect(instance).to.be();
    });

  });

}));
