/**
 * Qoodish API
 * Qoodih API. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QoodishApi);
  }
}(this, function(expect, QoodishApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QoodishApi.NewMap();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewMap', function() {
    it('should create an instance of NewMap', function() {
      // uncomment below and update the code to test NewMap
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be.a(QoodishApi.NewMap);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be();
    });

    it('should have the property baseId (base name: "base_id")', function() {
      // uncomment below and update the code to test the property baseId
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be();
    });

    it('should have the property baseName (base name: "base_name")', function() {
      // uncomment below and update the code to test the property baseName
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be();
    });

    it('should have the property _private (base name: "private")', function() {
      // uncomment below and update the code to test the property _private
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be();
    });

    it('should have the property invitable (base name: "invitable")', function() {
      // uncomment below and update the code to test the property invitable
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be();
    });

    it('should have the property shared (base name: "shared")', function() {
      // uncomment below and update the code to test the property shared
      //var instane = new QoodishApi.NewMap();
      //expect(instance).to.be();
    });

  });

}));
