/**
 * Qoodish API
 * Qoodih API. 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import MapDetail from './model/MapDetail';
import MapDetailBase from './model/MapDetailBase';
import NewMap from './model/NewMap';
import MapsApi from './api/MapsApi';


/**
* Qoodih_API_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var QoodishApi = require('index'); // See note below*.
* var xxxSvc = new QoodishApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new QoodishApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new QoodishApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new QoodishApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The MapDetail model constructor.
     * @property {module:model/MapDetail}
     */
    MapDetail,

    /**
     * The MapDetailBase model constructor.
     * @property {module:model/MapDetailBase}
     */
    MapDetailBase,

    /**
     * The NewMap model constructor.
     * @property {module:model/NewMap}
     */
    NewMap,

    /**
    * The MapsApi service constructor.
    * @property {module:api/MapsApi}
    */
    MapsApi
};
